name: autocheck

on:
  workflow_dispatch: # 手动触发
  schedule: 
    - cron: '0 9 * * *' # 北京时间17点05分

jobs: 
  check: 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install requirement
      run: |
          python -m pip install --upgrade pip
          pip install requests
    - name: check
      env: 
        PASSWORD: ${{ secrets.PASSWORD }}
        USERNAME: ${{ secrets.USERNAME }}
        WECHAT: ${{secrets.WECHAT}}
      run: python checkPy3.py
